(PC-21147)[API] feat: add djlint

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -226,5 +226,34 @@ cd ../
 ## END BACKOFFICE ##
 ####################
 
+################
+## BACKOFFICE V3 ##
+################
+cd $DIR/api
+STAGED_HTML_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep '^api/src/pcapi/routes/backoffice_v3/*' | grep 'html' | sed 's|^api\/||g')
+if [[ ! -z "$STAGED_HTML_FILES" ]]; then
+  # run stylelint on staged files
+  if [[ ! ",${DISABLED_BOV3_PRE_COMMIT_CHECKS}," =~ ",djlint," ]]; then
+    echo "Running dj formater and linter..."
+    djlint $STAGED_HTML_FILES --configuration src/pcapi/routes/backoffice_v3/.djlintrc --reformat
+    DJLINT_EXIT_CODE=$?
+
+    # add files auto-fixed by the linter
+    git add -f $STAGED_HTML_FILES
+
+    # check linter exit code
+    if [ $DJLINT_EXIT_CODE -ne 0 ]; then
+      echo "❌ Please fix djlint errors first: djlint $DIR/api/src/pcapi/routes/backoffice_v3/ --configuration $DIR/api/src/pcapi/routes/backoffice_v3/.djlintrc --reformat"
+      exit 1
+    else
+      echo "✅ djlint all good"
+    fi
+  fi
+fi
+cd ..
+####################
+## END BACKOFFICE ##
+####################
+
 # return 0-exit code
 exit 0
