(BSR)[API] chore: add poetry lock check on pre commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -207,5 +207,30 @@ cd ..
 ## END BACKOFFICE ##
 ####################
 
+#######################
+## CHECK DEPENDECIES ##
+#######################
+cd $DIR/api
+STAGED_PYPROJECT_TOML=$(git diff --cached --name-only --diff-filter=ACMR | grep -wE 'pyproject.toml|poetry.lock' | sed 's|^api\/||g')
+if [[ ! -z "$STAGED_PYPROJECT_TOML" ]]; then
+  # run stylelint on staged files
+  if [[ ! ",${DISABLED_API_PRE_COMMIT_CHECKS}," =~ ",check-dependencies," ]]; then
+    echo "Running check-dependencies..."
+    poetry check
+    CHECK_DEPENDENCIES_EXIT_CODE=$?
+
+    # add files auto-fixed by the linter
+    git add -f $STAGED_PYPROJECT_TOML
+
+    # check linter exit code
+    if [ $CHECK_DEPENDENCIES_EXIT_CODE -ne 0 ]; then
+      echo -e "❌ Please fix check-dependencies errors first. poetry.lock and pyproject.toml are not synced.\nIf the changes are wanted, run 'poetry lock' to update the dependencies and sync the lock file or 'poetry lock --no-update' to fix the lock file without updating unpinned dependencies"
+      exit 1
+    else
+      echo "✅ check-dependencies all good"
+    fi
+  fi
+fi
+
 # return 0-exit code
 exit 0
