(PC-28945) ci: fix return code in case of migration failure

diff --git a/.github/workflows/dev_on_workflow_deploy.yml b/.github/workflows/dev_on_workflow_deploy.yml
--- a/.github/workflows/dev_on_workflow_deploy.yml
+++ b/.github/workflows/dev_on_workflow_deploy.yml
@@ -139,11 +139,16 @@ jobs:
           export IMAGE="${IMAGE}:${VERSION}"
           export DATE=$(date +"%Y-%m-%d--%H-%M-%S")
           envsubst < .github/workflows/templates/pre-upgrade-job.yaml | kubectl -n ${{ inputs.environment }} apply -f -
-          while true;
-          do
-          kubectl logs -n ${{ inputs.environment }} -f jobs/pre-upgrade-${DATE} && break
-          done
-          kubectl wait --for=condition=complete --timeout=10900s -n ${{ inputs.environment }} jobs/pre-upgrade-${DATE}
+          # Next lines assume that job's backoffLimit is 0
+          kubectl logs -n ${{ inputs.environment }} -f jobs/pre-upgrade-${DATE} # This commands returns after first failure in job
+          kubectl wait --for=condition=complete jobs/pre-upgrade-${DATE} || kubectl wait --for=condition=failed jobs/pre-upgrade-${DATE} # Sanity check that the job is over
+          failure=$(kubectl get job -n ${{ inputs.environment }} jobs/pre-upgrade-${DATE} -o=jsonpath='{.status.conditions[?(@.type=="Failed")].status}') # Did the job fail or not so we can give correct return code
+          if [[ "$failure" == "True" ]]
+          then
+            exit 1
+          else
+            exit 0
+          fi
       - name: "Render manifests"
         run: |
           PASSCULTURE_USERNAME="oauth2accesstoken" \
@@ -184,11 +189,16 @@ jobs:
           export IMAGE="${IMAGE}:${VERSION}"
           export DATE=$(date +"%Y-%m-%d--%H-%M-%S")
           envsubst < .github/workflows/templates/post-upgrade-job.yaml | kubectl -n ${{ inputs.environment }} apply -f -
-          while true;
-          do
-          kubectl logs -n ${{ inputs.environment }} -f jobs/post-upgrade-${DATE} && break
-          done
-          kubectl wait --for=condition=complete --timeout=10900s -n ${{ inputs.environment }} jobs/post-upgrade-${DATE}
+          # Next lines assume that job's backoffLimit is 0
+          kubectl logs -n ${{ inputs.environment }} -f jobs/post-upgrade-${DATE} # This commands returns after first failure in job
+          kubectl wait --for=condition=complete jobs/post-upgrade-${DATE} || kubectl wait --for=condition=failed jobs/post-upgrade-${DATE} # Sanity check that the job is over
+          failure=$(kubectl get job -n ${{ inputs.environment }} jobs/post-upgrade-${DATE} -o=jsonpath='{.status.conditions[?(@.type=="Failed")].status}') # Did the job fail or not so we can give correct return code
+          if [[ "$failure" == "True" ]]
+          then
+            exit 1
+          else
+            exit 0
+          fi
 
   deploy-pro-on-testing-on-firebase:
     name: "Deploy pro on testing live channel"
