(BSR)[API] ci: fix tst env name

diff --git a/.github/workflows/dev_on_workflow_deploy.yml b/.github/workflows/dev_on_workflow_deploy.yml
--- a/.github/workflows/dev_on_workflow_deploy.yml
+++ b/.github/workflows/dev_on_workflow_deploy.yml
@@ -5,6 +5,9 @@ on:
       environment:
         type: string
         required: true
+      environment_short_name: # Required for deploying to new infra
+        type: string
+        required: false
       app_version:
         type: string
         required: true
@@ -58,6 +61,10 @@ on:
         required: true
       GCP_EHP_SERVICE_ACCOUNT:
         required: true
+      NEW_INFRA_WORKLOAD_IDENTITY_PROVIDER:
+        required: false
+      NEW_INFRA_PCAPI_DEPLOYER_SERVICE_ACCOUNT:
+        required: false
       PASSCULTURE_GITHUB_ACTION_APP_ID:
         required: true
         description: "Github Application ID to use to clone other repos"
@@ -68,9 +75,8 @@ on:
 jobs:
   deploy-api:
     name: "Deploy api"
-
     concurrency:
-      group: deploy-pcapi-${{ inputs.environment }}
+      group: deploy-pcapi-${{ inputs.environment }}-${{ inputs.is_new_infra }}
       cancel-in-progress: false
     runs-on: ubuntu-22.04
     environment: ${{ inputs.environment }}
@@ -98,10 +104,10 @@ jobs:
         if: ${{ inputs.deploy_api && inputs.is_new_infra }}
         uses: ./.github/actions/deploy-api-new-infra
         with:
-          environment: ${{ inputs.environment }}
+          environment: ${{ inputs.environment_short_name }}
           app_version: ${{ inputs.app_version }}
-          GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
-          GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
+          GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NEW_INFRA_WORKLOAD_IDENTITY_PROVIDER }}
+          GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.NEW_INFRA_PCAPI_DEPLOYER_SERVICE_ACCOUNT }}
           cluster_name: ${{ inputs.cluster_name }}
           cluster_scope: ${{ inputs.cluster_scope }}
           gcp_project_id: ${{ inputs.gcp_project_id }}
@@ -194,11 +200,12 @@ jobs:
       ENV: ${{ inputs.environment }}
       VERSION: ${{ inputs.app_version }}
 
-  apply-algolia-config:
+  apply-algolia-config-old-infra:
     name: "apply Algolia settings"
     needs: deploy-api
     if: |
       inputs.apply_algolia_config == true &&
+      !inputs.is_new_infra &&
       (needs.deploy-api.result == 'success' || needs.deploy-api.result == 'skipped')
     permissions:
       id-token: write
@@ -206,6 +213,7 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
       - uses: actions/checkout@v6
+
       - name: "Authentification to Google"
         uses: "google-github-actions/auth@v3"
         with:
@@ -237,6 +245,75 @@ jobs:
         with:
           service_account: ${{ steps.secrets.outputs.DEPLOYMENT_SA }}
           workload_identity_provider: ${{ steps.secrets.outputs.DEPLOYMENT_WORKLOAD_IDENTITY_PROVIDER }}
+
+      - name: "Connect to cluster"
+        uses: pass-culture/common-workflows/actions/pc-k8s-connect@pc-k8s-connect/v0.2.0
+        with:
+          cluster_scope: ${{ inputs.cluster_scope }}
+          cluster_environment: ${{ inputs.cluster_environment }}
+          api_token_github: ${{ steps.github-token.outputs.token }}
+
+      - name: "Configure algolia"
+        id: "set_algolia_settings"
+        uses: nick-fields/retry@v3
+        with:
+          timeout_minutes: 30
+          max_attempts: 3
+          command: |
+            ENV=${{ inputs.environment}}
+            POD_NAME=$(kubectl -n $ENV get pods -l role=api --field-selector=status.phase==Running -o json | jq -r '.items[] | "\(.metadata.name)"' | head -n 1)
+            FAIL=0
+            echo "flask commands runs on ${POD_NAME}"
+
+            if ! kubectl exec -it -n $ENV ${POD_NAME} -- flask set_algolia_settings artists --not-dry; then
+                echo "Failed to apply algolia settings for artists"
+                FAIL=1
+            fi
+            if ! kubectl exec -it -n $ENV ${POD_NAME} -- flask set_algolia_settings offers --not-dry; then
+                echo "Failed to apply algolia settings for offers"
+                FAIL=1
+            fi
+            if ! kubectl exec -it -n $ENV ${POD_NAME} -- flask set_algolia_settings collective_offers --not-dry; then
+                echo "Failed to apply algolia settings for collective_offers"
+                FAIL=1
+            fi
+            if ! kubectl exec -it -n $ENV ${POD_NAME} -- flask set_algolia_settings venues --not-dry; then
+                echo "Failed to apply algolia settings for venues"
+                FAIL=1
+            fi
+            exit $FAIL
+
+  apply-algolia-config:
+    name: "apply Algolia settings"
+    needs: deploy-api
+    if: |
+      inputs.apply_algolia_config == true &&
+      inputs.is_new_infra &&
+      (needs.deploy-api.result == 'success' || needs.deploy-api.result == 'skipped')
+    permissions:
+      id-token: write
+      contents: read
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v6
+
+      - name: "Authentification to Google with SA infra"
+        uses: "google-github-actions/auth@v3"
+        with:
+          workload_identity_provider: ${{ secrets.NEW_INFRA_WORKLOAD_IDENTITY_PROVIDER }}
+          service_account: ${{ secrets.NEW_INFRA_PCAPI_DEPLOYER_SERVICE_ACCOUNT }}
+
+      - name: Authenticate through github app ghactionci
+        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
+        id: github-token
+        with:
+          app-id: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID }}
+          private-key: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY }}
+          owner: ${{ github.repository_owner }}
+          repositories: |
+            pc-connect
+            pc-firestore-cli
+          permission-contents: read
 
       - name: "Connect to cluster"
         uses: pass-culture/common-workflows/actions/pc-k8s-connect@pc-k8s-connect/v0.2.0
