(BSR)[API] ci: improve mypy leaderboard GithubAction

diff --git a/.github/workflows/mypy-leaderboard.yml b/.github/workflows/mypy-leaderboard.yml
--- a/.github/workflows/mypy-leaderboard.yml
+++ b/.github/workflows/mypy-leaderboard.yml
@@ -5,6 +5,8 @@ on:
     branches:
       - master
     types: [closed]
+    paths:
+      - "api/src/**"
 
 jobs:
   get_mypy_score_on_merge:
@@ -19,16 +21,8 @@ jobs:
         uses: actions/checkout@v2.3.4
         with:
           persist-credentials: false
-      - name: Check changes
-        uses: dorny/paths-filter@v2
-        id: changes
-        with:
-          filters: |
-            src:
-              - 'api/**'
       - name: Calculate mypy diff
         id: mypy-score-calculator
-        if: steps.changes.outputs.src == 'true'
         run: |
           cd api
           this_branch_ignore_count="$(grep "type: ignore" -r src | wc -l)"
@@ -59,3 +53,8 @@ jobs:
               "author": "${{ needs.get_mypy_score_on_merge.outputs.author }}",
               "mypyDiff": ${{ needs.get_mypy_score_on_merge.outputs.mypy_score }}
           }'
+          res=$?
+          if test "$res" != "0"; then
+            echo "the curl command failed with: $res"
+            exit "$res"
+          fi
